# roles/setup-mongodb/tasks/main.yml
- name: Run MongoDB Container
  docker_container:
    name: mongodb
    image: mongo:latest
    state: started
    ports:
      - "27017:27017"
  when: docker_installed.changed == false
