---
- name: Pull image from repository
  docker_image:
    name: ngumonelson123/ngumo-backend:v1.1.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: ngumo-backend
    image: ngumonelson123/ngumo-backend:v1.1.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes